
package net.gabuchan.androidrecipe.recipe033;

import net.gabuchan.androidrecipe.R;
import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Toast;

public class Recipe033Activity extends Activity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_recipe_033);

        ArrayAdapter<String> adapter = new ArrayAdapter<String>(this,
                android.R.layout.simple_dropdown_item_1line, COUNTRIES);
        AutoCompleteTextView v = (AutoCompleteTextView)
                findViewById(R.id.auto_complete_text_view);
        v.setAdapter(adapter);
    }

    public void onButtonClick(View view) {
        AutoCompleteTextView v = (AutoCompleteTextView)
                findViewById(R.id.auto_complete_text_view);
        Toast.makeText(this, v.getText(), Toast.LENGTH_SHORT).show();
    }

    private static final String[] COUNTRIES = new String[] {
            "Afghanistan ",
            "Albania ",
            "Andorra ",
            "Antigua and Barbuda ",
            "Angola ",
            "Algeria ",
            "Argentina ",
            "Armenia ",
            "Aruba ",
            "Australia ",
            "Austria ",
            "Azerbaijan ",
            "Bahamas ",
            "Bangladesh ",
            "Barbados ",
            "Belgium ",
            "Belize ",
            "Benin ",
            "Bermuda ",
            "Bhutan ",
            "Bolivia ",
            "Bosnia-Herzegovina ",
            "Bahrain ",
            "Botswana ",
            "Belarus ",
            "Brazil ",
            "British Virgin Islands ",
            "Bulgaria ",
            "Burkina Faso ",
            "Burundi ",
            "Cameroon ",
            "Cambodia ",
            "Canada ",
            "Cayman Islands ",
            "Central Africa ",
            "Chad ",
            "Chile ",
            "China Republic ",
            "Chinese Taipei ",
            "Colombia ",
            "Comoros ",
            "Cape Verde ",
            "Congo ",
            "Cook Islands ",
            "Costa Rica ",
            "Cote-d´lvoire ",
            "Croatia ",
            "Cuba ",
            "Cyprus ",
            "Czech Republic ",
            "Denmark ",
            "Djibouti ",
            "Dominica ",
            "Dominican Republic ",
            "Ecuador ",
            "Arab Rep. of Egypt ",
            "El Salvador ",
            "Equatorial Guinea ",
            "Eritrea ",
            "Estonia ",
            "Ethiopia ",
            "Fiji ",
            "Finland ",
            "France ",
            "Gabon ",
            "The Gambia ",
            "Germany ",
            "Ghana ",
            "Great Britain ",
            "Guinea-Bissau ",
            "Georgia ",
            "Greece ",
            "Grenada ",
            "Guam ",
            "Guatemala ",
            "Guinea ",
            "Guyana ",
            "Haiti ",
            "Honduras ",
            "Hong Kong ",
            "Hungary ",
            "Iceland ",
            "India ",
            "Indonesia ",
            "Iran ",
            "Iraq ",
            "Ireland ",
            "Italy ",
            "Israel ",
            "Jamaica ",
            "Japan ",
            "Jordon ",
            "Kazakhstan ",
            "Kyrgyzstan ",
            "Kenya ",
            "Korea people Republic ",
            "Korea Democratic People Republic ",
            "Kuwait ",
            "Laos ",
            "Latvia ",
            "Saint Lucia ",
            "Lebanon ",
            "Lesotho ",
            "Libya ",
            "Lichtenstein ",
            "Luxembourg ",
            "Rep. of Macedonia ",
            "Madagascar ",
            "Malawi ",
            "Malaysia ",
            "Rep. of Moldova ",
            "Marshall Islands ",
            "Maldives ",
            "Malta ",
            "Mali ",
            "Mauritania ",
            "Mauritius ",
            "Mexico ",
            "Micronesia ",
            "Monaco ",
            "Montenegro ",
            "Mongolia ",
            "Morocco ",
            "Mozambique ",
            "Myanmar ",
            "Namibia ",
            "Nauru ",
            "Nepal ",
            "Netherlands ",
            "Netherlands Antilles ",
            "New Zealand ",
            "Nicaragua ",
            "Niger ",
            "Nigeria ",
            "Norway ",
            "Oman ",
            "Pakistan ",
            "Palau ",
            "Panama ",
            "Papua New Guinea ",
            "Palestine ",
            "Paraguay ",
            "Peru ",
            "Philippines ",
            "Poland ",
            "Portugal ",
            "Puerto Rico ",
            "Qatar ",
            "Romania ",
            "Rwanda ",
            "Saint Lucia ",
            "St. Vincent & Gr. ",
            "Saint Kitts and Nevis ",
            "Manu Samoa ",
            "American Samoa ",
            "San Marino ",
            "Sao Tome and Principe ",
            "Saudi Arabia ",
            "Seychelles ",
            "Sierra Leone ",
            "Senegal ",
            "Slovenia ",
            "Solomon Islands ",
            "South Africa ",
            "Sri Lanka ",
            "Slovakia ",
            "Swaziland ",
            "Serbia ",
            "Singapore ",
            "Spain ",
            "Sudan ",
            "Surinam ",
            "Syria ",
            "Sweden ",
            "Switzerland ",
            "Tanzania ",
            "Tonga ",
            "Thailand ",
            "Togo ",
            "Trinidad & Tobago ",
            "Tajikistan ",
            "Timor-Leste ",
            "Turkmenistan ",
            "Tunisia ",
            "Turkey ",
            "Tuvalu ",
            "Uganda ",
            "Ukraine ",
            "Unified Team ",
            "United Arab Emirates ",
            "U.S.S.R. ",
            "U.S.A. ",
            "US Virgin Islands ",
            "Uruguay ",
            "Uzbekistan ",
            "Vanuatu ",
            "Venezuela ",
            "Vietnam ",
            "Yemen ",
            "Zambia ",
            "Zimbabwe"
    };
}
